name: Hisan Daily Build

on:
  workflow_dispatch: # allows manual trigger from GitHub UI
    inputs:
      browser:
        type: choice
        required: true
        description: what browser should be used for test execution?
        default: Chrome
        options:
          - Chrome
          - Firefox
      url: 
        required: true
        description: Which url will be used?
        default: 'https://swtestacademy.com'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven

      - name: Build and test with Maven
        run: mvn -B clean test-Dbrowser=${{ github.event.inputs.browser }} -Durl=${{ github.event.inputs.url }}
